global_planner_node:
  ros__parameters:
    octomap_file: "maps/result_cleaned.bt"
    map_frame: "map"
    base_frame: "base_link"
    planning_mode: "3d"
    unknown_as_occupied: false
    robot_height_min: 0.1
    robot_height_max: 1.0
    start_z_override_enabled: false
    start_z_override: 0.0
    max_iterations: 500000

    publish_occupied_map_cloud: true
    occupied_map_cloud_topic: "/global_planner/occupied_map"
